### PR TITLE
compile on alpine:3.6 with alpine's 3.6 compiling resources

### PR DESCRIPTION
**Pull request by mluis**
Compiles.

### CODE REVIEW

**Comment by tsaitgaist** [comment]
GitHub is only used to mirror [osmocom projects](http://git.osmocom.org/). Please use the [mailing lists](https://lists.osmocom.org/mailman/listinfo) to [submit patches](http://projects.osmocom.org/projects/cellular-infrastructure/wiki/Coding_standards#Submitting-Patches).

**Comment by mluis** [comment]
sorry I have no time :(

**Comment by laf0rge** [comment]
regrding "no time": Well, we invest years of our life to create libosmocore and all the osmocom sotware, but then sending a single mail is already too much to ask for a contribution to a project you obviously seem to use and care about?

In any case, looking at it I don't understand it.  The commit log message is basically non-existsant. 
* What exactly is the error message you get during compile? 
* What is special about the alpine 3.6 compiler that it wouldn't support __always_inline?
* Is it maybe just as simple as including an additional header file?
* Does it work with "__attribute__((always_inline))" instead of __always_inline?

**Comment by mluis** [comment]
@laf0rge I totally understand a Maintainer situation and commitment over stuff. Now check this perspective: one guy that's compiling a tool that somehow got involved libosmocore in their dependencies's dependencies but do this recreationally because of his job has nothing to do with the actual subject. He takes the chance to report something he stumbled upon and solved it and used the means he's used to. Got lucky still cause there was a link to the libosmocore subject. It took like 1:30m.
Just the setup to "properly report a bug" on this is just too expensive to whom is not used to. (Following the email rules, patch rules, rules...)

Yeah, it's kinda ok. Believe me, I wish I was better paid and working on this lib related project for life.

Regarding your concerning:

- What exactly is the error message you get during compile?
```
error: expected '=', ',', ';', 'asm' or '__attribute__' before 'static'
```

- What is special about the alpine 3.6 compiler that it wouldn't support __always_inline?
```
$ gcc --version
gcc (Alpine 6.3.0) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- Is it maybe just as simple as including an additional header file?
```
i don't know
```

- Does it work with "attribute((always_inline))" instead of __always_inline?
```
No.
```

I'm recreating an Alpine's docker image so one can setup gr-* projects in just a minute or less more  the download time of the container.

**Comment by laf0rge** [comment]
I spent about 10mins to create an alpine-3.6 based Dockerfile with all libosmocore build dependencies, see http://git.osmocom.org/docker-playground/tree/alpine-build/Dockerfile

Based on this, it is possible to reproduce the build failure.

The patch that fixed the build in a proper way (keeping the semantics of always inlining those functions, as opposed to (I think) your proposed fix is in https://gerrit.osmocom.org/#/c/4162/ and has been merged to libosmocore.

Other projects also require similar patches (like https://git.alpinelinux.org/cgit/aports/plain/main/btrfs-progs/includes.patch) to build on alpine, so I still think there's something wrong/odd about alpine and it would be best to fix once and for all there, rather than patching all the various software projects that depend on __always_inline being present. Would be nice if you'd report this to alpine so they consider solving that once for all packages.

**Comment by mluis** [comment]
Open issues should be descriptive, complete as possible, and provide means of reproducibility. More important than that they must be on a backlog.

I believe all of us, like me, appreciate all those efforts.

Btw, I wasn't proposing any fix at all but I needed it compiled. So, why not? :) BR.

**Comment by mluis** [comment]
I have the issue closed both sides. lol

@laf0rge would you mind giving a look on this issue's reference and share an opinion pls?

Thanks.
BR

**Comment by mluis** [comment]
This is my actual gr-gsm.Dockerfile. I'm moving on to stock debian-based debian image. I just wanted to list IMSIs with my RTL-SDR though.

Thanks anyway.

```
FROM alpine:3.6

MAINTAINER Miguel Luís <mkxpto+docker@gmail.com>

# Set environment variables
ENV DEPS    git build-base cmake py-pip python2-dev autoconf automake libxml2-dev \
            lapack-dev gtk+3.0-dev libtool gfortran libx11-dev tiff tiff-dev \
            glu-dev libjpeg eudev-dev gstreamer1-dev gstreamer0.10-dev \
            gst-plugins-base1-dev gst-plugins-base0.10-dev flex bison pcsc-lite-dev wget \
            talloc-dev py-sip py-sip-dev liblogging-dev alsa-lib-dev py-libxslt cairo-dev py2-cairo-dev py3-cairo-dev \
            cython-dev zlib-dev libxslt-dev py-libxslt libressl-dev libressl qt-dev boost boost-random py-zmq \
            wxgtk-dev libxslt

# Install dependencies
RUN apk --update add --no-cache --virtual build-deps $DEPS 

# Install actual program
RUN printf "[list]\nformat=columns\n" >> /etc/pip.conf && \
    pip install PyBOMBS && \
    pybombs auto-config && \
    # @BUGGY!6.10.17 # pip install --upgrade git+https://github.com/gnuradio/pybombs.git && \
    pybombs recipes add-defaults && \
    sed -i 's/#\ \ cmd/\ \ cmd/g' ~/.pybombs/recipes/gr-recipes/python.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/x11.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libtiff.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libjpeg.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libevent.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libxml.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/ssl.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libudev.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/pcsclite.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/sip.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/alsa.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/qt4.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/pygtk.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/pyqt4.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/pyqwt5.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-etcetera/libboost-random.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/boost.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/python-zmq.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/atk.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/glib.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/gtk2.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/wxpython.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/libxslt.lwr && \
    sed -i 's/satisfy:/satisfy:\n\ \ cmd: true/g' ~/.pybombs/recipes/gr-recipes/pycairo.lwr && \
    ln -s /usr/include/libxml2/libxml/ /usr/include/libxml && \
    pybombs prefix init ./gnur -a gnur && \
    pybombs fetch libosmocore && \
    sed -i 's/__always_inline//g' `find -name  conv_acc_sse_impl.h` && \
    pybombs -p ./gnur install gr-gsm

# Set working directory
WORKDIR /data

# Define volumes
VOLUME /data

# Define
ENTRYPOINT  ["/bin/sh"]
```

**Comment by mluis** [comment]
I continued the project under an ubuntu's 2GB container [here](docker-gnuradio-ubuntu) if anyone find this interesting.

**Pull request closed without merging**
